### ISSUE TITLE
Source maps for TS files

### ISSUE THREAD

**Issue by Ciantic** [jbrantly/ts-jsx-loader#10]
I've noticed that `jsx-loader` generates source maps, it should be possible.

I've thought how to implement this already. It is required to combine several source maps from `reactTools.transformWithDetails`, then call `this.callback(null, code, sourcemap)` inside the index.js instead of returning value.

Though I've yet to figure out how to combine source maps and offset them.

**Comment by jbrantly** [comment]
Agree this would be nice. My experience with working with the `source-map` package is limited but I'll see if I can't figure it out.

**Comment by jbrantly** [comment]
I doubt I will wind up implementing this, particularly since this project will hopefully be deprecated with native JSX support in TypeScript. Just FYI. I am open to pull requests though.

**Comment by jbrantly** [comment]
Closing this since native JSX support is for sure coming in TypeScript and this project will be deprecated.
