### ISSUE TITLE
Add support for embedded expressions in template strings

### ISSUE THREAD

**Issue by silhouettes** [jbrantly/ts-jsx-loader#12]
The great thing about using the React.jsx() syntax over a TypeScript fork such as jsx-typescript is that it doesn't break intellisense and syntax highlighting in existing TypeScript editors. The tradeoff, though, is that we get no language support within our jsx strings. However, we could leverage embedded expressions within template strings to add autocompletion for embedded javascript:

![image](https://cloud.githubusercontent.com/assets/696206/7755691/0a711718-ffab-11e4-81e3-ff9f360dd231.png)

This syntax is very similar to the simple brace syntax used in JSX, and can be implemented as a simple find and replace of '${}' to '{}' before hitting the jsx compiler. It also won't break any existing use cases - within ES6 template strings, '${' unambiguously refers to the beginning of an embedded expression. Because the actual value of the expression is evaluated at run-time, this currently has no meaning (and will fail) when inside a React.jsx() call, which is essentially a compile-time directive. 

Our team would really like to use this feature so I've implemented this here:
https://github.com/silhouettes/ts-jsx-loader/tree/embedded-expressions

If you're happy with this change, I can submit a pull request, or I'm happy to make further changes if you'd like to see any improvements! I've added test cases already and have also tested it on a demo React project.

**Comment by jbrantly** [comment]
This is a really good idea! I would definitely say go ahead and create a pull request.

My only concern with the implementation as-is would be balancing close-braces. If I'm not mistaken, the current regex `jsx = jsx.replace(/\$\{(.*?)\}/gm, "{$1}")` will break if given something like this:

```
style=${{color: this.props.color }}
```

I'm not sure if that's a problem we can overcome using only regex though.

**Comment by jbrantly** [comment]
Supporting this fully is probably going to require the usage of a real parser instead of regex.

For my own notes: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#traversing-the-ast-with-a-little-linter

**Comment by silhouettes** [comment]
Ah that's a good point - this is actually really funny because I tried it on my own project (which has stuff like "${{}}") and it worked fine, only because the substitution works the same way regardless of where you parse the closing brace.

It could be more honest to just not bother matching closing braces and just do the substitution from '${' to '{', although that's weaker at catching the following cases:

${ /* comment with ${ */ this.static }
${ this.static + "${" }

So, given the limits of regex, I think I'll leave it in the pull request as a token attempt to match the closing brace that shouldn't have any terrible side effects. I can see it working differently from expected in the following cases:

${ "string with } ${" + this.static }          // The '$' in the string unnecessarily stripped out
${{color: this.props.color} /* ${ */ }        // The '$' in the comment unnecessarily stripped out

**Comment by jbrantly** [comment]
Added in v0.2.1
