### ISSUE TITLE
error trying to use ES7 spread properties

### ISSUE THREAD

**Issue by flyon** [jbrantly/ts-jsx-loader#14]
I'm trying to use this:

`React.jsx(`<li {...this.props.childProps} className="test">test</li>`)``

and I use 

```
loaders: [
   { test: /\.ts$/, loader: 'ts-loader!ts-jsx-loader?harmony=true' } 
]
```

But I get an error: Property '__spread ' does not exist on type 'typeof React'.
Does that have to do with the definition file? Or with the ts-jsx-loader?

**Comment by jbrantly** [comment]
`__spread` is defined in the two definition files `react-jsx.d.ts` and `react-addons-jsx.d.ts`. Make sure you have one (or both) of those referenced.

**Comment by jbrantly** [comment]
If that still doesn't work for some reason, could you share how you import React?

**Comment by flyon** [comment]
ah, sorry, not sure how I missed those. That should fix it, tnx!
